#!/bin/bash

. testsuite/defs.sh

runme
sleep 15
wifi GOT_IP
sleep 10
rm -f $TEST_FOLDER/exception.txt
mqttsub cmnd/TempSensor/OTA test_exception
sleep 5

if [ ! -f $TEST_FOLDER/exception.txt ]; then
    echo "Exception dump not found"
    exit 1
fi

rm -f $TEST_FOLDER/exception.txt
