#!/bin/bash

. testsuite/defs.sh

runme
sleep 15
wifi GOT_IP
sleep 10 
mqttsub cmnd/TempSensor/OTA open
sleep 1

TESTFILE=$TEST_FOLDER/testbase.sim
TARGETFILE=$TEST_FOLDER/fwupload.sim
NOOTA=$TEST_FOLDER/noota.sim

rm -f $TARGETFILE $NOOTA

# Top-folder new file

dd if=/dev/urandom of=$TESTFILE bs=$((4096 * (10 + $RANDOM % 10))) count=1
chmod 400 $TESTFILE
./otafwtool 127.0.0.1 $TESTFILE rstw1 && ( echo "otatool should have failed"; exit 1 )
sleep 5
./otafwtool 127.0.0.1 $TESTFILE zero2 && ( echo "otatool should have failed"; exit 1 )
sleep 5
./otafwtool 127.0.0.1 $TESTFILE rstw2 && ( echo "otatool should have failed"; exit 1 )
sleep 5
./otafwtool 127.0.0.1 $TESTFILE timeout2 && ( echo "otatool should have failed"; exit 1 )
sleep 5
./otafwtool 127.0.0.1 $TESTFILE order && ( echo "otatool should have failed"; exit 1 )
sleep 5
./otafwtool 127.0.0.1 $TESTFILE prevhash && ( echo "otatool should have failed"; exit 1 )
sleep 5
./otafwtool 127.0.0.1 $TESTFILE neuhash && ( echo "otatool should have failed"; exit 1 )
sleep 5
touch $NOOTA
./otafwtool 127.0.0.1 $TESTFILE && ( echo "otatool should have failed"; exit 1 )
sleep 5
