#!/bin/bash

. testsuite/defs.sh

runme
sleep 5

wifi GOT_IP

./entool bla ble 0 rx 60 ts
sleep 1
./entool bla ble 0 tx data payload "stat/TNow/Value\n1"
./entool bla ble 0 rx 5 ts confirm 1 tid lasttx
sleep 1
./entool bla ble 0 tx data payload "moo" badhmac 1
sleep 1
./entool bla ble 0 tx data payload "moo" badcrypt 1
sleep 1
./entool bla ble 0 tx data payload "moo" badgroup 1
sleep 1
./entool bla ble 0 tx data payload "moo" badlen 1
sleep 1
./entool bla ble 0 tx data payload "moo" badversion 1
sleep 1
./entool bla ble 0 tx badtype
sleep 1
wifi UNDEF_ERROR
advance 60000
sleep 5
wifi GOT_IP
sleep 5
./entool bla ble 0 tx pairreq
./entool bla ble 0 rx 5 ts
sleep 3
./entool bla ble 0 tx wakeup
./entool bla ble 0 rx 5 ts confirm 1 tid lasttx
sleep 3
./entool bla ble 0 tx ping
./entool bla ble 0 rx 5 ts confirm 1 tid lasttx
./entool bla ble 0 tx data payload "stat/TNow/Value\n1" sametid 1
# ./entool bla ble 0 norx 1

sleep 5
quit
