#!/bin/bash

. testsuite/defs.sh

runme
sleep 5

wifi GOT_IP

./entool bla ble 0 rx 60 ts
sleep 1
./entool bla ble 0 tx data payload "stat/TNow/Value\n1"
./entool bla ble 0 rx 5 ts confirm 1 tid lasttx

sleep 5
quit
