#!/bin/bash

. testsuite/defs.sh

mcp23017f
runme
sleep 5
wifi GOT_IP
sleep 10
assert mqtt stat/H2OControl/Malfunction 2
assert mqtt stat/H2OControl/CoarseLevelPct 100
mcp23017f
sleep 3
advance $(( 10 * 60 * 1000 ))
sleep 3
assert mqtt stat/H2OControl/Malfunction 2
mcp23017nf
sleep 3
advance $(( 10 * 60 * 1000 ))
sleep 3
assert mqtt stat/H2OControl/Malfunction 0
sleep 5
mcp23017f
sleep 5
assert mqtt stat/H2OControl/Malfunction 4
sleep 3
mcp23017f
advance $(( 10 * 60 * 1000 ))
sleep 3
assert mqtt stat/H2OControl/Malfunction 6
mcp23017nf
sleep 3
advance $(( 10 * 60 * 1000 ))
sleep 3
assert mqtt stat/H2OControl/Malfunction 0
mcp23017 251
sleep 7 # 4 seconds of debounce
assert mqtt stat/H2OControl/CoarseLevelPct 60
assert mqtt stat/H2OControl/Malfunction 1
mcp23017 248
sleep 7
assert mqtt stat/H2OControl/CoarseLevelPct 60
assert mqtt stat/H2OControl/Malfunction 0
