#!/bin/bash

. testsuite/defs.sh

runme

touch ${TEST_FOLDER}/tnowpsend.sim
./entool flush
./entool bla ble 5 rx 90 pairreq
./entool bla ble 5 tx ts
sleep 1
touch ${TEST_FOLDER}/tnowpsend.sim
./entool bla ble 5 rx 60 data
./entool bla ble 5 tx ts confirm lasttid
sleep 1
./entool bla ble 5 tx ts confirm lasttid # repeated to detect replay
sleep 1
./entool bla ble 5 tx ts confirm lasttid badlen3 1
sleep 1
./entool bla ble 5 tx ts badhmac 1
sleep 1
./entool bla ble 5 tx ts badcrypt 1
sleep 1
./entool bla ble 5 tx ts badlen 1
sleep 1
./entool bla ble 5 tx ts badversion 1
sleep 1
./entool bla ble 5 tx ts badgroup 1
sleep 1
./entool bla ble 5 tx ts badlen2 1
sleep 1
./entool bla ble 5 tx badtypec
sleep 1
./entool bla ble 5 tx ts
sleep 1
./entool bla ble 5 tx ts sametid 1
sleep 2
./entool bla ble 5 tx ts
sleep 1
./entool bla ble 5 tx ts replay 1
sleep 1
./entool bla ble 5 tx ts tsoffset 1000000
./entool bla ble 5 tx ts tsoffset 1000000 # DUT should send only one ping
sleep 1
./entool bla ble 5 rx 2 ping
./entool bla ble 5 tx ts confirm lasttid tsoffset 1000000
sleep 1
echo "confirm" > ${TEST_FOLDER}/tnowpsend.sim
./entool bla ble 5 rx 60 data
./entool bla ble 5 tx ts confirm lasttid tsoffset 1000000
sleep 1
echo "exception" > ${TEST_FOLDER}/espnow_sendfail.sim
echo "confirm" > ${TEST_FOLDER}/tnowpsend.sim
./entool bla ble 5 norx 1

sleep 5

quit
