#!/bin/bash

. testsuite/defs.sh

runme

touch ${TEST_FOLDER}/tnowpsend.sim
./entool flush
./entool bla ble 5 rx 90 pairreq
./entool bla ble 5 tx ts
sleep 1
touch ${TEST_FOLDER}/tnowpsend.sim
./entool bla ble 5 rx 60 data

quit
