#!/bin/bash

. testsuite/defs.sh

runme
sleep 5

wifi GOT_IP
sleep 60

assert mqtt stat/Energy/V 220.0
assert mqtt stat/Energy/A 4.0
assert mqtt stat/Energy/VA 880.0
assert mqtt stat/Energy/W 1.0
assert mqtt stat/Energy/Malfunction 0

pzemf fail4 # read energy failure 

sleep 15

assert mqtt stat/Energy/Malfunction 4

pzemf fail1 # init failure

sleep 15

assert mqtt stat/Energy/Malfunction 1

pzemf clean

sleep 20

assert mqtt stat/Energy/Malfunction 0

mqttsub cmnd/Energy/Ticker on

sleep 5

assert mqtt stat/Energy/Vnow 220.0
assert mqtt stat/Energy/Anow 4.0
assert mqtt stat/Energy/VAnow 880.0
assert mqtt stat/Energy/Wnow 1.0

mqttsub cmnd/Energy/Ticker off
sleep 5

quit
