#!/bin/bash

. testsuite/defs.sh

runme
sleep 5

wifi GOT_IP
sleep 60

assert mqtt stat/Energy/V 222.1
assert mqtt stat/Energy/A 4.8
assert mqtt stat/Energy/PowerFactor 0.70
assert mqtt stat/Energy/Wh 150.0
assert mqtt stat/Energy/W 0.0
assert mqtt stat/Energy/Malfunction 0

pzemf fail4 # read energy failure 

sleep 15

assert mqtt stat/Energy/Malfunction 4

pzemf fail1 # init failure

sleep 15

assert mqtt stat/Energy/Malfunction 1

pzemf fail2 # reset energy failure

sleep 20

assert mqtt stat/Energy/Malfunction 2

pzemf clean

sleep 20

assert mqtt stat/Energy/Malfunction 0

timeout 5s nc localhost 1338 || echo

sleep 5

quit
