#!/bin/bash

. testsuite/defs.sh

# Manuals
gpio 26 1
gpio 34 1
gpio 33 1
gpio 35 1
runme
sleep 5
# Switches/relays
assert gpio 16 0
assert gpio 2 0
assert gpio 32 0
assert gpio 12 0
wifi GOT_IP
sleep 5

# Pulse Manual 0
gpio 26 0
sleep 1
gpio 26 1
assert gpio 16 1
sleep 5
gpio 26 0
sleep 1
gpio 26 1
assert gpio 16 0

# Flaky switch
gpio 26 0
sleep 0.2
gpio 26 1
sleep 1
assert gpio 16 0

# Nil program
mqttsub cmnd/Switch/Program ";"
sleep 1
assert mqtt stat/Switch/ProgramCompilation "Program is nil"

mqttsub cmnd/Switch/Program "P:a"
sleep 1
assert mqtt stat/Switch/ProgramCompilation "Program manual unexp"

mqttsub cmnd/Switch/Program "P:a:b"
sleep 1
assert mqtt stat/Switch/ProgramCompilation "Program manual# unexp"

mqttsub cmnd/Switch/Program "0:X:b"
sleep 1
assert mqtt stat/Switch/ProgramCompilation "Program kind unexp"

mqttsub cmnd/Switch/Program "0:P:+0"
sleep 1
assert mqtt stat/Switch/ProgramCompilation "Phase list len unexp"

mqttsub cmnd/Switch/Program "0:P:+0/0"
sleep 1
assert mqtt stat/Switch/ProgramCompilation "Switch len unexp"

mqttsub cmnd/Switch/Program "0:P:+0/x0"
sleep 1
assert mqtt stat/Switch/ProgramCompilation "Switch sign unexp"

mqttsub cmnd/Switch/Program "0:P:+0/-a"
sleep 1
assert mqtt stat/Switch/ProgramCompilation "Phase switch# unexp"

mqttsub cmnd/Switch/Program "0:P:+1/-1"
sleep 1
assert mqtt stat/Switch/ProgramCompilation "Success"
assert mqtt "stat/Switch/Program " "0:P:+1/-1"

# Pulse Manual 0, should change switch 1 now
gpio 26 0
sleep 1
gpio 26 1
assert gpio 16 0
assert gpio 2 1
# Another pulse
sleep 5
gpio 26 0
sleep 1
gpio 26 1
assert gpio 16 0
assert gpio 2 0

mqttsub cmnd/Switch/0/State 1
sleep 1
assert gpio 16 1

mqttsub cmnd/Switch/1/State On
sleep 1
assert gpio 2 1

mqttsub cmnd/Switch/0/State off
mqttsub cmnd/Switch/1/State 0
assert gpio 16 0
assert gpio 2 0

sleep 5
quit
