#!/bin/bash

. testsuite/defs.sh

runme
mqttfail connect
sleep 10
wifi GOT_IP
sleep 5
advance 30000

mqttfail ping
sleep 10
advance 60000
sleep 10
advance 30000

mqttfail checkmsg
sleep 10
advance 60000
sleep 10
advance 30000

mqttfail publish
advance 60000
sleep 10
advance 30000

quit
