#!/bin/bash

. testsuite/defs.sh

runme
sleep 5
wifi GOT_IP
sleep 10 
mqttsub cmnd/TempSensor/OTA invalid
sleep 1
mqttsub cmnd/TempSensor/OTA open
sleep 1

# Top-folder new file

TESTFILE=otatest111.sim
rm -f $TESTFILE
dd if=/dev/urandom of=$TESTFILE bs=$((1 + $RANDOM % 5000)) count=1
chmod 400 $TESTFILE
[ ! -e $TEST_FOLDER/$TESTFILE ] || ( echo "File preexistant"; exit 1 )
./otatool 127.0.0.1 send $TESTFILE
while [ ! -f $TEST_FOLDER/$TESTFILE ]; do
        sleep 1
done

sleep 3
if ! cmp $TESTFILE $TEST_FOLDER/$TESTFILE; then
    echo "Source and destination file different"
    chmod 644 $TESTFILE
    exit 1
fi

chmod 644 $TESTFILE
rm -f $TESTFILE


# Top-folder existing file

TESTFILE=otatest111.sim
rm -f $TESTFILE
dd if=/dev/urandom of=$TESTFILE bs=$((1 + $RANDOM % 5000)) count=1
[ -f $TEST_FOLDER/$TESTFILE ] || ( echo "File not preexistant"; exit 1 )
./otatool 127.0.0.1 send $TESTFILE
while [ -f $TEST_FOLDER/tmppiggy ] || [ ! -f $TEST_FOLDER/$TESTFILE ]; do
    sleep 1
done

sleep 3
if ! cmp $TESTFILE $TEST_FOLDER/$TESTFILE; then
    echo "Source and destination file different"
    exit 1
fi

rm -f $TESTFILE


# New file in new folder

TESTFILE=folder.sim/folder.sim2/otatest112.sim
rm -rf folder.sim
mkdir -p folder.sim/folder.sim2
dd if=/dev/urandom of=$TESTFILE bs=$((1 + $RANDOM % 5000)) count=1
[ ! -e $TEST_FOLDER/folder.sim ] || ( echo "Target folder preexistant"; exit 1 )
./otatool 127.0.0.1 send $TESTFILE
while [ ! -f $TEST_FOLDER/$TESTFILE ]; do
        sleep 1
done

sleep 3
if ! cmp $TESTFILE $TEST_FOLDER/$TESTFILE; then
    echo "Source and destination file different"
    exit 1
fi


# New file in existing folder

TESTFILE=folder.sim/folder.sim2/otatest113.sim
rm -rf folder.sim
# target folder recreated here
mkdir -p folder.sim/folder.sim2
dd if=/dev/urandom of=$TESTFILE bs=$((1 + $RANDOM % 5000)) count=1
[ -d $TEST_FOLDER/folder.sim/folder.sim2 ] || ( echo "Target folder not preexistant"; exit 1 )
./otatool 127.0.0.1 send $TESTFILE
while [ ! -f $TEST_FOLDER/$TESTFILE ]; do
        sleep 1
done
sleep 3
if ! cmp $TESTFILE $TEST_FOLDER/$TESTFILE; then
    echo "Source and destination file different"
    exit 1
fi


# Existing file in existing folder

TESTFILE=folder.sim/folder.sim2/otatest113.sim
rm -rf folder.sim
# target folder recreated here
mkdir -p folder.sim/folder.sim2
dd if=/dev/urandom of=$TESTFILE bs=$((1 + $RANDOM % 5000)) count=1
[ -f $TEST_FOLDER/$TESTFILE ] || ( echo "Target file not preexistant"; exit 1 )
./otatool 127.0.0.1 send $TESTFILE
while [ ! -f $TEST_FOLDER/$TESTFILE ]; do
        sleep 1
done

sleep 3
if ! cmp $TESTFILE $TEST_FOLDER/$TESTFILE; then
    echo "Source and destination file different"
    exit 1
fi

REMOTE_HASH=$(./otatool 127.0.0.1 hash $TESTFILE)
LOCAL_HASH=$(sha1sum $TEST_FOLDER/$TESTFILE | cut -f 1 -d ' ')

if [ "$REMOTE_HASH" != "$LOCAL_HASH" ]; then
    echo "Hash wrong"
    exit 1
fi

REMOTE_HASH=$(./otatool 127.0.0.1 hash foobar)

if [ "$REMOTE_HASH" != "0000000000000000000000000000000000000000" ]; then
    echo "Non-existent hash wrong"
    exit 1
fi

# Top-folder zero-sized file

TESTFILE=otatest115.sim
rm -f $TESTFILE
touch $TESTFILE
chmod 400 $TESTFILE
[ ! -e $TEST_FOLDER/$TESTFILE ] || ( echo "File preexistant"; exit 1 )
./otatool 127.0.0.1 send $TESTFILE
while [ ! -f $TEST_FOLDER/$TESTFILE ]; do
        sleep 1
done

sleep 3
if ! cmp $TESTFILE $TEST_FOLDER/$TESTFILE; then
    echo "Source and destination file different"
    chmod 644 $TESTFILE
    exit 1
fi

REMOTE_HASH=$(./otatool 127.0.0.1 hash $TESTFILE)

if [ "$REMOTE_HASH" != "da39a3ee5e6b4b0d3255bfef95601890afd80709" ]; then
    echo "Empty file hash wrong"
    exit 1
fi

chmod 644 $TESTFILE
rm -f $TESTFILE


rm -rf folder.sim

mqttsub cmnd/TempSensor/OTA reboot
sleep 5
