#!/bin/bash

set -e

DEVTYPE="$1"
IP="$2"
FORCE="$3"

if ! [ -f profiles/${DEVTYPE}/manifest.ota ]; then
    echo "Error: device type has no manifest.ota"
    exit 1
fi

if ! ./otatool "$profiles/IP" flavor; then
    REMOTEDEVTYPE="old"
else
    REMOTEDEVTYPE=$(./otatool "$IP" flavor)
fi

if [ "$DEVTYPE" != "$REMOTEDEVTYPE" ]; then
    echo "Flavor type does not match" $DEVTYPE $REMOTEDEVTYPE
    if [ "$FORCE" != "force" ]; then
            exit 1
    fi
fi

(while true; do

    read a || break
    localfile=$(echo $a | cut -f 1 -d ' ')  
    remotefile=$(echo $a | cut -f 2 -d ' ')
    if [ "$localfile" = "" ]; then
        continue
    fi
    if ! [ -f "$localfile" ]; then
        echo "Local file $localfile does not exist"
        exit 1
    fi
    if [ "$remotefile" = "" ]; then
        remotefile="$localfile"
    fi
    localhash=$(sha1sum $localfile | cut -f 1 -d ' ')
    echo "Hash of local  $localfile: $localhash"
    remotehash=$(./otatool "$IP" hash $remotefile 2>/dev/null || echo Error)
    if [ "$remotehash" = "Error" ]; then
        echo "Error getting remote hash"
        exit 1
    fi
    echo "Hash of remote $remotefile: $remotehash"
    if [ "$remotehash" != "$localhash" ]; then
        echo "...Updating"
        if ! ./otatool "$IP" send $localfile $remotefile; then
            echo "Error sending file"
            exit 1
        fi
    fi

done) < profiles/${DEVTYPE}/manifest.ota
