#!/bin/bash

. testsuite/defs.sh

runme
sleep 5
wifi GOT_IP
sleep 10 
mqttsub cmnd/TempSensor/OTA invalid
sleep 1
touch bla.upl ble.upl
mqttsub cmnd/TempSensor/OTA open
sleep 1

if [ -f bla.upl ] || [ -f ble.upl ]; then
    echo ".upl files not removed"
    exit 1
fi

# Top-folder new file

TESTFILE=otatest111.sim
INTERMFILE=$(echo $TEST_FOLDER/$TESTFILE | sed 's/\//$/g' | sed 's/$/.upl/')
rm -f $TESTFILE
dd if=/dev/urandom of=$TESTFILE bs=$((1 + $RANDOM % 5000)) count=1
chmod 400 $TESTFILE
[ ! -e $TEST_FOLDER/$TESTFILE ] || ( echo "File preexistant"; exit 1 )
./otatool 127.0.0.1 send $TESTFILE =

while [ ! -f $INTERMFILE ]; do
    sleep 1
done

if [ -f $TEST_FOLDER/$TESTFILE ]; then
    echo "File before commit"
    exit 1
fi

mqttsub cmnd/TempSensor/OTA commit
sleep 1

while [ ! -f $TEST_FOLDER/$TESTFILE ]; do
    sleep 1
done

if [ -f $INTERMFILE ]; then
    echo "Intermediate file still presentt"
    exit 1
fi

sleep 3
if ! cmp $TESTFILE $TEST_FOLDER/$TESTFILE; then
    echo "Source and destination file different"
    chmod 644 $TESTFILE
    exit 1
fi

chmod 644 $TESTFILE
rm -f $TESTFILE

# Top-folder existing file

TESTFILE=otatest111.sim
INTERMFILE=$(echo $TEST_FOLDER/$TESTFILE | sed 's/\//$/g' | sed 's/$/.upl/')
rm -f $TESTFILE
dd if=/dev/urandom of=$TESTFILE bs=$((1 + $RANDOM % 5000)) count=1
[ -f $TEST_FOLDER/$TESTFILE ] || ( echo "File not preexistant"; exit 1 )
./otatool 127.0.0.1 send $TESTFILE =
while [ -f $TEST_FOLDER/tmppiggy ] || [ ! -f $INTERMFILE ]; do
    sleep 1
done

if cmp $TESTFILE $TEST_FOLDER/$TESTFILE; then
    echo "Source and destination file equal"
    exit 1
fi

mqttsub cmnd/TempSensor/OTA commit
sleep 3

if ! cmp $TESTFILE $TEST_FOLDER/$TESTFILE; then
    echo "Source and destination file different"
    exit 1
fi

if [ -f $INTERMFILE ]; then
    echo "Intermediate file still present"
    exit 1
fi

rm -f $TESTFILE

# New file in new folder

TESTFILE=folder.sim/folder.sim2/otatest112.sim
INTERMFILE=$(echo $TEST_FOLDER/$TESTFILE | sed 's/\//$/g' | sed 's/$/.upl/')
rm -rf folder.sim
mkdir -p folder.sim/folder.sim2
dd if=/dev/urandom of=$TESTFILE bs=$((1 + $RANDOM % 5000)) count=1
[ ! -e $TEST_FOLDER/folder.sim ] || ( echo "Target folder preexistant"; exit 1 )
./otatool 127.0.0.1 send $TESTFILE =
while [ ! -f $INTERMFILE ]; do
        sleep 1
done

if [ -e $TEST_FOLDER/$TESTFILE ]; then
    echo "File before commit"
    exit 1
fi

mqttsub cmnd/TempSensor/OTA commit
sleep 3

if ! cmp $TESTFILE $TEST_FOLDER/$TESTFILE; then
    echo "Source and destination file different"
    exit 1
fi

if [ -f $INTERMFILE ]; then
    echo "Intermediate file still present"
    exit 1
fi


# New file in existing folder

TESTFILE=folder.sim/folder.sim2/otatest113.sim
INTERMFILE=$(echo $TEST_FOLDER/$TESTFILE | sed 's/\//$/g' | sed 's/$/.upl/')
rm -rf folder.sim
# target folder recreated here
mkdir -p folder.sim/folder.sim2
dd if=/dev/urandom of=$TESTFILE bs=$((1 + $RANDOM % 5000)) count=1
[ -d $TEST_FOLDER/folder.sim/folder.sim2 ] || ( echo "Target folder not preexistant"; exit 1 )
./otatool 127.0.0.1 send $TESTFILE =
while [ ! -f $INTERMFILE ]; do
        sleep 1
done

if [ -e $TEST_FOLDER/$TESTFILE ]; then
    echo "File before commit"
    exit 1
fi

mqttsub cmnd/TempSensor/OTA commit
sleep 3
if ! cmp $TESTFILE $TEST_FOLDER/$TESTFILE; then
    echo "Source and destination file different"
    exit 1
fi

if [ -f $INTERMFILE ]; then
    echo "Intermediate file still present"
    exit 1
fi


# Existing file in existing folder

TESTFILE=folder.sim/folder.sim2/otatest113.sim
INTERMFILE=$(echo $TEST_FOLDER/$TESTFILE | sed 's/\//$/g' | sed 's/$/.upl/')
rm -rf folder.sim
# target folder recreated here
mkdir -p folder.sim/folder.sim2
dd if=/dev/urandom of=$TESTFILE bs=$((1 + $RANDOM % 5000)) count=1
[ -f $TEST_FOLDER/$TESTFILE ] || ( echo "Target file not preexistant"; exit 1 )
./otatool 127.0.0.1 send $TESTFILE =
while [ ! -f $INTERMFILE ]; do
        sleep 1
done

if cmp $TESTFILE $TEST_FOLDER/$TESTFILE; then
    echo "Source and destination file equal"
    exit 1
fi
mqttsub cmnd/TempSensor/OTA commit
sleep 3
if ! cmp $TESTFILE $TEST_FOLDER/$TESTFILE; then
    echo "Source and destination file different"
    exit 1
fi

if [ -f $INTERMFILE ]; then
    echo "Intermediate file still present"
    exit 1
fi

REMOTE_HASH=$(./otatool 127.0.0.1 hash $TESTFILE)
LOCAL_HASH=$(sha1sum $TEST_FOLDER/$TESTFILE | cut -f 1 -d ' ')

if [ "$REMOTE_HASH" != "$LOCAL_HASH" ]; then
    echo "Hash wrong"
    exit 1
fi

REMOTE_HASH=$(./otatool 127.0.0.1 hash foobar)

if [ "$REMOTE_HASH" != "0000000000000000000000000000000000000000" ]; then
    echo "Non-existent hash wrong"
    exit 1
fi

# Top-folder zero-sized file

TESTFILE=otatest115.sim
INTERMFILE=$(echo $TEST_FOLDER/$TESTFILE | sed 's/\//$/g' | sed 's/$/.upl/')
rm -f $TESTFILE
touch $TESTFILE
chmod 400 $TESTFILE
[ ! -e $TEST_FOLDER/$TESTFILE ] || ( echo "File preexistant"; exit 1 )
./otatool 127.0.0.1 send $TESTFILE =
while [ ! -f $INTERMFILE ]; do
        sleep 1
done

if [ -e $TEST_FOLDER/$TESTFILE ]; then
    echo "File before commit"
    exit 1
fi

mqttsub cmnd/TempSensor/OTA commit
sleep 3
if ! cmp $TESTFILE $TEST_FOLDER/$TESTFILE; then
    echo "Source and destination file different"
    chmod 644 $TESTFILE
    exit 1
fi

if [ -f $INTERMFILE ]; then
    echo "Intermediate file still present"
    exit 1
fi

REMOTE_HASH=$(./otatool 127.0.0.1 hash $TESTFILE)

if [ "$REMOTE_HASH" != "da39a3ee5e6b4b0d3255bfef95601890afd80709" ]; then
    echo "Empty file hash wrong"
    exit 1
fi

if ! [ -f $TEST_FOLDER/$TESTFILE ]; then
    echo "Empty file not in place"
    exit 1
fi

./otatool 127.0.0.1 rm $TESTFILE

if [ -f $TEST_FOLDER/$TESTFILE ]; then
    echo "Empty file not removed"
    exit 1
fi

./otatool 127.0.0.1 rm $TESTFILE

if [ -f $TEST_FOLDER/$TESTFILE ]; then
    echo "Empty file not removed II"
    exit 1
fi

chmod 644 $TESTFILE
rm -f $TESTFILE

if ! ./otatool 127.0.0.1 flavor; then
    echo "Error getting flavor"
    exit 1
fi

GOTFLAVOR=$(./otatool 127.0.0.1 flavor)
if [ "$GOTFLAVOR" != "weather" ]; then
    echo "Wrong flavor"
    exit 1
fi

rm -rf folder.sim

mqttsub cmnd/TempSensor/OTA msg_reboot
sleep 2

mqttsub cmnd/TempSensor/OTA msg_exception
sleep 2

mqttsub cmnd/TempSensor/OTA stats
sleep 2

mqttsub cmnd/TempSensor/OTA msg_rm 
sleep 2

mqttsub cmnd/TempSensor/OTA reboot
sleep 5
