#!/bin/bash

. testsuite/defs.sh

# should be discarded
./entool bla ble 0 tx ts
touch $TEST_FOLDER/pair.txt

runme

./entool flush
./entool bla ble 5 rx 90 pairreq
./entool bla ble 5 tx ts
./entool bla ble 5 rx 60 data

sleep 3
quit

sleep 3
hx711f init
runme

./entool flush
./entool bla ble 5 rx 90 wakeup
./entool bla ble 5 tx ts confirm lasttid
./entool bla ble 5 rx 60 data

sleep 3
quit

sleep 3
hx711f read
runme

./entool flush
./entool bla ble 5 rx 90 wakeup
./entool bla ble 5 tx ts confirm lasttid
./entool bla ble 5 rx 60 data

sleep 3
quit

sleep 3
hx711f poweroff
runme

./entool flush
./entool bla ble 5 rx 90 wakeup
./entool bla ble 5 tx ts confirm lasttid
./entool bla ble 5 rx 60 data

sleep 3
quit

sleep 3
hx711f unstable
runme

./entool flush
./entool bla ble 5 rx 90 wakeup
./entool bla ble 5 tx ts confirm lasttid
./entool bla ble 5 rx 90 data

sleep 3
quit

sleep 3
hx711f unstable2
runme

./entool flush
./entool bla ble 5 rx 90 wakeup
./entool bla ble 5 tx ts confirm lasttid
./entool bla ble 5 rx 120 data

sleep 3
quit
