#!/bin/bash

. testsuite/defs.sh

runme
sleep 15

wifi GOT_IP

./entool bla ble 0 rx 60 ts
sleep 1
./entool bla ble 0 tx data payload "stat/LPScale/Weight\n7.0"
./entool bla ble 0 rx 5 ts confirm 1 tid lasttx
sleep 2
./entool bla ble 0 tx data payload "stat/LPScale/Weight\nbah"
./entool bla ble 0 rx 5 ts confirm 1 tid lasttx
sleep 3
./entool bla ble 0 tx data payload "stat/LPScale/Malfunction\nbah"
./entool bla ble 0 rx 5 ts confirm 1 tid lasttx
sleep 1
./entool bla ble 0 tx data payload "stat/LPScale/Malfunction\n1"
./entool bla ble 0 rx 5 ts confirm 1 tid lasttx
sleep 3
./entool bla ble 0 tx data payload "stat/LPScale/Bah\n1"
./entool bla ble 0 rx 5 ts confirm 1 tid lasttx
sleep 1
./entool bla ble 0 tx data payload "blabla"
./entool bla ble 0 rx 5 ts confirm 1 tid lasttx
sleep 1
./entool bla ble 0 tx data payload "errôu" encoding latin1
./entool bla ble 0 rx 5 ts confirm 1 tid lasttx

sleep 5
quit
